kind: Service
apiVersion: v1
metadata:
  name: helidon-starter 
  labels:
    app: helidon-starter
spec:
  type: NodePort
  selector:
    app: helidon-starter
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-starter
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: helidon-starter
  template:
    metadata:
      labels:
        app: helidon-starter
        version: v1
    spec:
      containers:
        - name: helidon-starter
          image: helidon-starter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080